### ISSUE TITLE
[FEAT] Disable KAMSVNC menu while pre-defining quality setting using a config file

### ISSUE THREAD

**Issue by ne0YT** [linuxserver/docker-baseimage-kasmvnc#12]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to be able to disable the sidebar menu of kasmvnc so it is not shown to the user while pre-definign the quality settings.

as a side-question maybe. how do you setup the audio feature to work using kasm as I don't see this in the normal KASM setup.
I read in your description, that you use pulseaudio and the Kclient helper application. but how could I set this up on my non-Docker KASM setup?

### Reason for change

It would make the usage easier for non-technical end-users.

**Comment by thelamer** [comment]
I have no plans for a kiosk mode at this time, but in general take a look at the embedding options passed in the kclient: 
https://github.com/linuxserver/kclient/blob/master/public/index.html#L17

As for audio KasmVNC has no audio support, but Kasm Workspaces uses a helper in the container to achieve this I do something similar but I pipe the raw pulseaudio data to the browser vs ffmpeg encoded aac. 
In general the audio button needs to be clicked for browser support, Safari in particular has problems playing audio unless the playaudio is called directly from a user button click. Some browsers can intercept a simple page interaction and use that to activate audio.
