### ISSUE TITLE
[BUG] Git and PulseAudio node.js Versions are Incompatible (in Arch)

### ISSUE THREAD

**Issue by ixion396** [linuxserver/docker-baseimage-kasmvnc#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Node module version of PulseAudio is 115 while the version of git in the core repo depends on node 21 with module version 120. Installing the latest version of git breaks the installation of Pulse. Fixable by using ``pacman -S git`` instead of ``pacman -Syu git``.

### Steps To Reproduce

1. pacman -Syu git
2. restart container

### Docker creation

```bash
services:
  archtop:
    image: lscr.io/linuxserver/webtop:arch-i3
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    networks:
      - tunnel
    environment:
      PUID: 1028
      PGID: 100
      TZ: America/New_York
      TITLE: ArchTop
      CUSTOM_PORT: 3389
      GOMP_CPU_AFFINITY: "1-23"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /home/x/arch/scripts/init.d:/custom-cont-init.d:ro
      - /home/x/arch/scripts/services.d:/custom-services.d:ro
      - /home/x/arch:/config
      - /var/run/docker.sock:/var/run/docker.sock
    shm_size: "1gb"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

### Container logs

```bash
n/a
```

**Comment by thelamer** [comment]
This kind of stuff happens all the time with arch due to it's rolling nature, there is no magic bullet but we do the best we can by only triggering downstream builds once the base is updated. 
The current `lscr.io/linuxserver/webtop:arch-i3` has functional audio.
