### ISSUE TITLE
Hide VNC cursor

### ISSUE THREAD

**Issue by kevinmnm** [linuxserver/docker-baseimage-kasmvnc#44]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would be great if there's a simple way to pass `-nocursor` [option](https://www.x.org/wiki/AdvancedTopicsFAQ/) to x11 or similar to be able to hide VNC cursor. Wondering if there's an existing feature for this already?

### Reason for change

Scalability

**Comment by thelamer** [comment]
No there is not and I do not know how to achieve this without this being in KasmVNC. (it controls the X-11 sessions)
