### ISSUE TITLE
[FEAT] Add key bindings for window decoration

### ISSUE THREAD

**Issue by stevenwfoley** [linuxserver/docker-baseimage-kasmvnc#45]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add the below described Decoration related key bindings to the <keyboard> section of the /etc/xdg/openbox/rc.xml file:
http://openbox.org/wiki/Help:Actions#ToggleDecorations

I'm mainly interested in the ToggleDecoration, but the other two would be nice for completeness.
I tested adding the entry to my local rc.xml file and it functions as expected.

### Reason for change

Provide a quick method to remove and restore window decoration.

### Proposed code change

`
  <keybind key="A-S-d">
    <action name="ToggleDecorations"/>
  </keybind>
  <keybind key="C-S-d">
    <action name="Decorate"/>
  </keybind>
  <keybind key="C-S-d">
    <action name="Undecorate"/>
  </keybind>
`

**Comment by thelamer** [comment]
Just so you know there is an env var for disabling decoration with `-e NO_DECOR=true`, but having a keyboard shortcut for this is not a bad idea by default in the base images.

**Comment by stevenwfoley** [comment]
Thanks, I did find that variable, but the issue I ran into immediatly was a popup dialog in an app (firefox) went full screen, with no way to undecorate, so I was stuck. The hotkey would solve this.

**Comment by thelamer** [comment]
This has been added to the baseimages it will take time to waterfall to everything downstream.
