### ISSUE TITLE
[FEAT] Custom favicon

### ISSUE THREAD

**Issue by strboul** [linuxserver/docker-baseimage-kasmvnc#51]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

There's a default favicon on the application. It'd be nice to allow users to set a custom favicon e.g. via environment variables.

Besides, other services using the base image VNC (such as Firefox) can also benefit from this. For instance, showing Firefox logo in the browser's tab instead of the default favicon would be more pleasant. 
So for the other services, I'd propose to add a default favicon of the application as well as the option to change the default favicon.

### Reason for change

It's nice to see tabs distinguished by different icons rather than all of them have the same icon and it's also more customization possibilities for the end user.

### Proposed code change

The favicon is directly accessible at e.g. `localhost:3000/favicon.ico`. It could be possible to tell nginx to use a different favicon.

What can be added to the file `/etc/nginx/http.d/default.conf`:

```nginx
location /favicon.ico {
    alias /path/to/favicon.ico; # that path comes from the environment variables
}
```

**Comment by thelamer** [comment]
`-v /path/to/local/favicon.ico:/kclient/public/favicon.ico` would work.

**Comment by strboul** [comment]
> `-v /path/to/local/favicon.ico:/kclient/public/favicon.ico` would work.

This works well. Maybe we should just document it in the README under e.g. Optional run configurations, e.g. [Firefox](https://github.com/linuxserver/docker-firefox/blob/master/readme-vars.yml#L71).
