### ISSUE TITLE
[FEAT] upload size limit

### ISSUE THREAD

**Issue by asch99** [linuxserver/docker-baseimage-kasmvnc#59]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'd like to be able to upload larger files using the included kclient. Right now it is limitted to 200M. I can change the hardcoded 200M in kclient/index.js, but that is not enough to be really able to upload files >200M. Ideally, the max size should be configurable

### Reason for change

It gives the opportunity to upload larger data files e.g. big images for more diverse applications

**Comment by thelamer** [comment]
We should stop using the websocket method and chunk up the files properly and support any size.
