### ISSUE TITLE
/etc/nsswitch.conf is missing entries 

### ISSUE THREAD

**Issue by deepio-oc** [linuxserver/docker-baseimage-kasmvnc#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the nsswitch file in previous version had following:
```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files
group:          files
shadow:         files
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

But in recent docker images, it now has:
```
➜  ~ docker run -it --entrypoint bash ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy                
root@adb5ec1d8759:/# cat /etc/nsswitch.conf 
hosts: files dns

➜  ~ docker run -it --entrypoint bash ubuntu:jammy                                     
root@1481c83e48f2:/# cat /etc/nsswitch.conf 
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files
group:          files
shadow:         files
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis

```

### Expected Behavior

The nsswitch file should not be modified from the base ubuntu image. 

### Steps To Reproduce

1. run ubuntu base image and check nsswitch.conf. 
2. run ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy

### Environment

```markdown
- OS:
- How docker service was installed:
```

### Docker creation

```bash
docker run -it --entrypoint bash ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy
```

### Container logs

```bash
root@adb5ec1d8759:/# cat /etc/nsswitch.conf 
hosts: files dns
```

**Comment by deepio-oc** [comment]
this looks like is intentional because of following line in dockerfile:
```
 echo 'hosts: files dns' > /etc/nsswitch.conf 
 ```
 Without password/shadow entries in /etc/nsswitch.conf, we are not able to fetch entries from sssd. If this is required for some scenario, then maybe backup can be kept in /etc.

**Comment by thelamer** [comment]
We specifically make this modification for DinD compatibility: 
https://github.com/linuxserver/docker-baseimage-kasmvnc#kasmvnc-base-images-from-linuxserver
It is needed for the DinD hack and is applied across the board to all the GUI images. (when you run these images in priv mode they fire up Docker in Docker) 
To be frank I am not 100% certain of the external consequences, can you explain what this breaks ?

**Comment by deepio-oc** [comment]
We use this webtop image as base for our VNC server. We added multi-user support using SSSD (SSSD talks to AD to fetch users). For SSSD to work, we need following in /etc/nsswitch.conf

passwd:         files      sss

This is automatically done when we install libnss-sss package but this is broken with recent changes since there is no passed entry anymore.

**Comment by thelamer** [comment]
You could pretty easily have an init mod add that to the file: 
https://github.com/linuxserver/docker-mods/

This container was never designed with multi user support in mind, it's main goal is to automate the delivery of a Linux desktop to a web browser for a single user.
