### ISSUE TITLE
[FEAT] Upgrade to KasmVNC 1.3.1

### ISSUE THREAD

**Issue by nadiamoe** [linuxserver/docker-baseimage-kasmvnc#60]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Currently packaged KasmVNC version has a bug that causes it to misbehave with firefox clients >=124. This was reported upstream in https://github.com/kasmtech/KasmVNC/issues/219, and has now been fixed in https://github.com/kasmtech/KasmVNC/releases/tag/v1.3.1.

I tried to make a PR for this, but I couldn't wrap my head around the build system. Specifically, I was not able to find in the codebase how to produce a `debianbookworm-` or `ubuntunoble-` image.

### Reason for change

Bugfixes

**Comment by nadiamoe** [comment]
Okay, took me quite some time to find that the `debianbookworm` and other non-alpine tags are just different branches on this repo. I'll try to build this locally and ensure that the latest release works fine :)

**Comment by nadiamoe** [comment]
_Activity taking place_

**Comment by renato-dl** [comment]
It seems to me that the issue is still present. I am using `ubuntujammy` and KasmVNC version is still 1.3.0.
Am I missing something?
