### ISSUE TITLE
[FEAT] File drag and drop support 

### ISSUE THREAD

**Issue by Pastitas** [linuxserver/docker-baseimage-kasmvnc#67]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add an togglable option to make the app upload automatically any files that are dragged and dropped there in the main page (maybe using some default upload folder setting) .

If this could somehow be integrated with the vnc host to drag the same file to the used application inside would be amazing but that seems way more complex, maybe that could be a future improvement

### Reason for change

Right now there's no action associated with dragging and dropping files on kasmvnc webpage, instead the default action by the browser is done. Also in the settings menu there's an option for file upload that, when that specific window is open, allows for file uploads via drag and drop.

 This makes sense for applications in which you'd normally want to drag and drop a file into, like https://github.com/linuxserver/docker-orcaslicer

**Comment by j0nnymoe** [comment]
You would need to send this feature request to Kasm.

**Comment by Pastitas** [comment]
Opened an issue and was told that the kasmvnc is not the component that does this, so I assumed it was on your side
https://github.com/kasmtech/KasmVNC/issues/250
Where can I open this then if its not there nor here?
It's unclear to me where the feature I'm currently using for uploads comes from

**Comment by j0nnymoe** [comment]
Our baseimage consumes this repo: https://github.com/kasmtech/noVNC/ .

I'll tag in @thelamer as he'll have more knowledge on all this.
Side note to what you're wanting to do, I would suggest mounting an additional volume which you keep your 3d print files in.
Personally I have `/models` mounted which is shared with a few other things.

**Comment by Pastitas** [comment]
Thanks, I've created an issue there and closed the other one, this might be closed then aswell when they confirm it's their feature
https://github.com/kasmtech/noVNC/issues/109

**Comment by thelamer** [comment]
The KasmVNC protocol does not have any file functionality that is something we bolt on with Kclient. Draggable overlay divs generally can block other specific interaction with the page depending on the browser (keyboard or mouse input) which is why it is scoped to the file browser modal.
