### ISSUE TITLE
Flatpak Runtime Integration/Interface.

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [linuxserver/docker-baseimage-kasmvnc#7]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Better or wider Flatpak support.

### Reason for change

The "community" preferences for Flatpak over Snap.

### Proposed code change

https://github.com/refi64/flatpod

**Comment by thelamer** [comment]
I don't understand you want this container to be converted to a flatpak compatible application ?
I'm not up on flatpak/snap is web based apps normal for their ecosystem? Last I was up to speed they focused on desktop apps.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> I don't understand you want this container to be converted to a flatpak compatible application ?
> I'm not up on flatpak/snap is web based apps normal for their ecosystem? Last I was up to speed they focused on desktop apps. 



Does this clarify? 

Its straight from their Readme.

Convert podman containers to Flatpak runtimes! This was built for development purposes, in order to be able to use the large container ecosystem for Flatpak development, as I'm on Silverblue; the runtimes aren't really intended for publishing (you can try if you want though).

**Comment by OpenOS-Project-Creator-Founder** [comment]
Basically, people would love WayDroid as Flatpak. 

Shown with these 2 links.

https://github.com/waydroid/waydroid/issues/64

https://discourse.flathub.org/t/waydroid-android-apps-on-linux-request/2040

So a good friend of mine has WayDroid packaged as Docker which is Podman compatible...

https://github.com/sickcodes/dock-droid

Though he also has Windows & MacOS/iOS available as Docker Images also.

https://github.com/sickcodes/windows-docker-machine

https://github.com/sickcodes/Docker-OSX

https://github.com/sickcodes/Docker-eyeOS

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Basically, people would love WayDroid as Flatpak. 
> 
> Shown with these 2 links.
> 
> https://github.com/waydroid/waydroid/issues/64
> 
> https://discourse.flathub.org/t/waydroid-android-apps-on-linux-request/2040
> 
> So a good friend of mine has WayDroid packaged as Docker, which is Podman compatible...
> 
> https://github.com/sickcodes/dock-droid
> 
> Though he also has Windows & MacOS/iOS available as Docker Images also.
> 
> https://github.com/sickcodes/windows-docker-machine
> 
> https://github.com/sickcodes/Docker-OSX
> 
> https://github.com/sickcodes/Docker-eyeOS

So basically, convert any Docker Image, including the ones into Flatpak using FlatPod.

Though Atoms; https://github.com/AtomsDevs/Atoms / https://flathub.org/apps/pm.mirko.Atoms

&&

Distrobox; https://github.com/89luca89/distrobox

Offer there's still much to do...

**Comment by thelamer** [comment]
No sorry there are a lot of links here, but it does not answer my question. 
You want flatpak support in this baseimage? (would require FUSE privved up container) 
You want this openbox baseimage  and all the supported distros packaged as a flatpack?

**Comment by OpenOS-Project-Creator-Founder** [comment]
> No sorry there are a lot of links here, but it does not answer my question. [ Sorry those a part of the Docker/Podman variant of the core project I'm working on. We are building both LXC/LXD & Docker/Podman variants of the project. To have the same headless features but feature KDE Plasma as the graphical front-end. ]



> You want flatpak support in this baseimage? (would require FUSE privved up container) [ Flatpak "for the community" & LXC/LXD for Ubuntu Flavours" ]




> You want this openbox baseimage  and all the supported distros packaged as a flatpack? [ YES ]


Would you like more background information on the projects goals?

**Comment by thelamer** [comment]
We make docker containers, we only test and officially support the containerd runtime. 
This is not a decision to play favorites, it is all we as a small development team are capable of. 
The code is there though and I encourage you to setup some github actions to ingest all the images out there and package them up how you see fit, it should be pretty simple code you can pass an array of endpoints to watch on a schedule for sha changes in their respective registries. You can also run it for free on Github with actions and their container registry or release file storage for distribution. We just cannot test and support a new runtime.
