### ISSUE TITLE
[Password] How can we disable kasm_user / password in docker image

### ISSUE THREAD

**Issue by yoongeon1206** [linuxserver/docker-baseimage-kasmvnc#76]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

currently, the kasm docker image has a default user and a password. I just try to disable or remove them in dockerfile.

### Reason for change

We are looking for a way for developers to easily access KASM without receiving the ID password
It is necessary to delete the ID and password set by default as the first step.
I want to make the developer approach the KASM service without access ID and password.

### Proposed code change

Is there a way to easily delete ID/PASSWORD settings from Dockerfile?

**Comment by thelamer** [comment]
Why not just use port 3000 or 3001 ? Those have no auth by default.

**Comment by drizuid** [comment]
no response from OP after proposed solution from the dev of this container. closing
