### ISSUE TITLE
[BUG] kasminit fails - missing ip command

### ISSUE THREAD

**Issue by djarbz** [linuxserver/docker-baseimage-kasmvnc#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the fedora-kde image, the container will not startup due to missing of the `ip` command.

See my notes in https://github.com/linuxserver/docker-webtop/issues/240

### Expected Behavior

Container should start and present the desktop via KasmVNC.

### Steps To Reproduce

Deploy and start a workspace using webtop:fedora-kde

### Environment

```markdown
- OS: Fedora 39
- How docker service was installed: dnf
```

### Docker creation

```bash
Kasm Workspace
```

### Container logs

```bash
/kasminit: line 79: ip: command not found
/kasminit: line 79: ip: command not found
/kasminit: line 79: ip: command not found
/kasminit: line 79: ip: command not found
/kasminit: line 79: ip: command not found
/kasminit: line 79: ip: command not found
/kasminit: line 79: ip: command not found
/kasminit: line 79: ip: command not found
...
```

**Comment by thelamer** [comment]
Yep specific to Fedora, my fault. Pull latest and the webtops have been rebuilt.

**Comment by djarbz** [comment]
I can confirm this is working, thank you.
