### ISSUE TITLE
[BUG] Performance issues

### ISSUE THREAD

**Issue by ne0YT** [linuxserver/docker-baseimage-kasmvnc#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when there is a background image but also without one when there is an image on a website for example, moving around windows is quite laggy. especially compared to my kasmvnc setup directly on the same hardware.

### Expected Behavior

everything is smooth like I'm used to using kasmvnc directly

### Steps To Reproduce

docker run -d --name webtop1 \
  -e SUBFOLDER=/1/ \
  -v /dev/shm:/dev/shm \
  --security-opt seccomp=unconfined \
  linuxserver/webtop:latest
  
  but it happens also when building it myself as described in the readme

### Environment

```markdown
- OS:Ubuntu Server 22.04
- How docker service was installed:
https://docs.docker.com/engine/install/ubuntu/
```

### Docker creation

```bash
docker run -d --name webtop1 \
  -e SUBFOLDER=/1/ \
  -v /dev/shm:/dev/shm \
  --security-opt seccomp=unconfined \
  linuxserver/webtop:latest

but it happens also when building it myself as described in the readme
```

### Container logs

```bash
..
```

**Comment by thelamer** [comment]
What is the hardware, also test with a webtop more similar to your host like `linuxserver/webtop:debian-xfce`

**Comment by ne0YT** [comment]
@thelamer it is actually running a bit better using linuxserver/webtop:debian-xfce but still not quite there
directly on the VM I get always 30+ fps (there are always more then 60 sessions open) while using "linuxserver/webtop:debian-xfce" only results in max 15 fps often less (7ish) (I test playing the same youtube video. KASM-settings are the same.
this is while I access the docker-version "directly" while having authentik & a seperate caddy in front of my kasm.

the hardware is a proxmox vm with 12vcpus and 24GB of RAM

physical cpu:
88 x Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (2 Sockets)

is there a simple way I can just get the audio feature on my kasm setup? I tried to run the project https://github.com/linuxserver/kclient on top of my KASM but smh I failed (only the files feature was working, the session itself wasn't)

**Comment by ne0YT** [comment]
hm.. network seems to be worse on the docker version:
![image](https://github.com/user-attachments/assets/498c940c-8b0d-4b1d-90d1-737fa3572737)

this is from the same client but -> kasm directly on the vm:
![image](https://github.com/user-attachments/assets/5775e012-6b34-42b1-9b32-a21ca3b0d448)

both playing this youtube short:
https://www.youtube.com/shorts/v_uPguVDNPg

they are both running on the same host

**Comment by ne0YT** [comment]
another test.. (I used wireguard to access the docker kasm..)
this is when I also put it behind the same caddy:
![image](https://github.com/user-attachments/assets/78ae1a78-8cb1-4af0-b0ec-41411b8fff56)

and this when I access it directly via a 1:1 NAT:
![image](https://github.com/user-attachments/assets/a2ea6934-c1a0-47e5-93b2-783865d18162)

**Comment by thelamer** [comment]
Docker adds overhead but it should not be significant like this.
Two things I noticed is you are mounting in shm, don't do that and you are not forwarding a port, can you post your actual run or compose command ?

**Comment by ne0YT** [comment]
@thelamer 
oh yeah maybe it's the nginx:
```
docker run -d --name webtop1 \
  -e SUBFOLDER=/1/ \
  -v /dev/shm:/dev/shm \
  --security-opt seccomp=unconfined \
  linuxserver/webtop:debian-xfce

docker run -d --name webtop2 \
  -e SUBFOLDER=/2/ \
  -v /dev/shm:/dev/shm \
  --security-opt seccomp=unconfined \
  linuxserver/webtop:debian-xfce

docker run -d --name webtop3 \
  -e SUBFOLDER=/3/ \
  -v /dev/shm:/dev/shm \
  --security-opt seccomp=unconfined \
  linuxserver/webtop:debian-xfce

docker run -d --name nginx-proxy \
  -p 3001:443 \
  -v /opt/kasm/nginx.conf.d:/etc/nginx/conf.d \
  -v /opt/kasm/ssl:/etc/nginx/ssl \
  --link webtop1 --link webtop2 --link webtop3 \
  nginx:latest
  ```
  
  nginx conf:
  ```
    server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location /1/ {
        proxy_pass http://webtop1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /2/ {
        proxy_pass http://webtop2:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /3/ {
        proxy_pass http://webtop3:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
```

**Comment by thelamer** [comment]
Rip everything down to the basics 

```
docker run --rm -it -p 3000:3000 --shm-size=1gb linuxserver/webtop:debian-xfce bash
```
Land on that host port 3000, that is your baseline test, go from there.

**Comment by ne0YT** [comment]
@thelamer I killed all the dockers and tried that, accessing it directly using http
![image](https://github.com/user-attachments/assets/9f5e28dd-e3ce-4443-9814-cf45801a58f3)

it doesn't change anything I can notice performance-wise

and I need a way to share the shm-memory to be able to run as many sessions as possible with the least amount of ram used.

**Comment by thelamer** [comment]
Use a webpage like this for your baseline https://blurbusters.com/category/testufo/ just moving images. But with that old xeon and 12 threads I dunno, like I don't know how I can help you here. You would have to discover the method that works.
Also just to make sure when you say host you mean it is running in the same VM right? Cause kasmvnc is threaded and will use all the threads you have, if one has 88 and one has 12 the 88 one will work much better.

**Comment by ne0YT** [comment]
that also doesn't change a thing.
I cloned the setup and then stopped everything and only started one docker like you posted on port 3000. I get between 21 and 23 fps (testufo). then i rebooted and tested using my normal kasm setup I connected with my notebook to three of my sessions and hit 29-35 fps on all of them at the same time.

**Comment by ne0YT** [comment]
yay.. mystery solved..
it's the settings.. now I just need to mod the kasm files form the container like I do on the host and I can use the docker..
