### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by slowfound** [linuxserver/docker-baseimage-kasmvnc#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Manifest for `ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye` cannot be found even though it worked until yesterday.

```
load metadata for ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye:
------
failed to solve: ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye: failed to resolve source metadata for ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye: no match for platform in manifest: not found
```

But the manifest for the current latest version when specified can be found and works:

```
docker pull ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye-8446af38-ls104
debianbullseye-8446af38-ls104: Pulling from linuxserver/baseimage-kasmvnc
3cb9336d0acf: Already exists
82b04c31e307: Already exists
cb4860b164e4: Already exists
09d1965a0983: Already exists
cc987275b418: Already exists
9ed48f8965c6: Already exists
68b5ffb578a9: Pull complete
0f64e7aaebc6: Pull complete
a480cf71e662: Pull complete
1c885a653680: Pull complete
Digest: sha256:c0a70d010865cc9281aab466853a5417c1a94ca5b765e4e4f4d1db1bd006e799
Status: Downloaded newer image for ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye-8446af38-ls104
ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye-8446af38-ls104
```

### Expected Behavior

It should pull the appropriate image.

### Steps To Reproduce

A simple line in `Dockerfile` file:

```
FROM ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye AS base
```

You can also clone this branch in my repo:

https://github.com/sesto-dev/metatrader5-linux-django-docker/tree/chapter-1

with:

```
git clone -b chapter-1 --single-branch https://github.com/sesto-dev/metatrader5-linux-django-docker
```

### Environment

```markdown
- OS: Ubuntu 24.04
- How docker service was installed: distro's packagemanager
```

### Docker creation

```bash
docker-compose.yml:
https://github.com/sesto-dev/metatrader5-linux-django-docker/blob/chapter-1/docker-compose.yml

Dockerfile:
https://github.com/sesto-dev/metatrader5-linux-django-docker/blob/chapter-1/Dockerfile
```

### Container logs

```bash
It does not pull the appropriate image so the image does not build.
```

**Comment by Roxedus** [comment]
This is intended, as the branch is deprecated. https://github.com/linuxserver/docker-baseimage-kasmvnc/pull/92
The invalidation of the non-version tag is how we make consumers aware of this. If you need to keep using bookworm, you need to specify a specific tag.

**Comment by AmirhsFar** [comment]
The issue is still present and I am getting the exact same error. Please guide us through resolving it.

**Comment by slowfound** [comment]
> The issue is still present and I am getting the exact same error. Please guide us through resolving it.

You can use this:

`FROM ghcr.io/linuxserver/baseimage-kasmvnc:debianbullseye-8446af38-ls104 AS base`
